version: '3.8'

services:
  app:
    build: .
    ports:
      - '3011:3011'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - TZ=Asia/Seoul
    restart: unless-stopped
